server:
  port: 8085
spring:
  application:
    name: service1-stringGenerator
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
feign:
  hystrix:    enabled: true